#! /bin/bash

set -eux

cd /root
# move default config files to volumes if missing
if [ ! -f /var/spamassassin/user_prefs ]; then
  cp spamassassin_template/user_prefs /var/spamassassin/user_prefs
fi

if [ ! -f imap_config/imap_account_config.lua ]; then
  cp imap_config_template/* imap_config/
fi

# start services, etc...
echo "starting services"
service rsyslog start

{
  set -eux

  echo "fixing permissions, just in case..."
  chown -R debian-spamd:mail /var/spamassassin

  echo "updating SpamAssassin rules"
  sa-update -v --refreshmirrors
  echo "running sa-learn"
  sa-learn --force-expire

  logger "starting spamassassin"
  service spamassassin start

  echo "running learm_spam"
  lua5.3 learn_spam.lua

  echo "starting CRON"
  service cron start
} 2>&1 | /usr/bin/logger -e -s -t startup

tail -n 0 -F /var/log/*.log
